name: Build and Deploy Python App to Azure Web App

env:
  AZURE_WEBAPP_NAME: 'ApoloWhatsapp'
  PYTHON_VERSION: '3.11'
  PACKAGE_DIR: 'package'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create package directory and install dependencies
        run: |
          pip install --target="./${{ env.PACKAGE_DIR }}" -r requirements.txt

      - name: Create deployment package
        run: |
          # Copy application files
          cp whatsapp_bot.py ./${{ env.PACKAGE_DIR }}/
          cp startup.sh ./${{ env.PACKAGE_DIR }}/
          # Copy data directory
          cp -r apolo_faiss ./${{ env.PACKAGE_DIR }}/
          # Create the zip file
          cd ${{ env.PACKAGE_DIR }}
          zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'release.zip'